Feat/cyclical special event
LifeAdventurer/generators pull request #45
Opened 2024-12-03 15:10 UTC by tobiichi3227

Add suport for cyclical date for special event.
Allow users to avoid updating the same special event dates every year.
Enhance the robustness of special event data parsing.

2024-12-03 15:52 UTC, LifeAdventurer requested changes
Wish you could separate `special.json` into three files for better organization:

1. `static_special.json` for events with fixed dates.
2. `cyclical_special.json` for recurring events (e.g., holidays like Thanksgiving and Mother's Day).
3. `custom_special.json` for user-defined or custom events.

This separation would improve clarity and make managing different event types more efficient. Let me know what you think.

2024-12-03 15:52 UTC, LifeAdventurer commented on fortune_generator/js/fortune.js
> +    const num = [36, 236, 233, 221]; // NOTE: for dev
It looks like the line for splitting and parsing the IP address is commented out, and a hardcoded value is used instead. Please remove this line.

2024-12-03 15:52 UTC, LifeAdventurer commented on fortune_generator/json/special.json
>        "event": "學測 Day 1",
Please remove the following three events.

2024-12-03 15:52 UTC, LifeAdventurer commented on fortune_generator/json/special.json
> +      "triggerDate": {
中秋節 (Mid-Autumn Festival) does not fall on the same day every year as it follows the lunar calendar.

2024-12-03 15:52 UTC, LifeAdventurer commented on fortune_generator/json/special.json
> +      },
感恩節 is celebrated on the fourth Thursday of November.

2024-12-03 15:52 UTC, LifeAdventurer commented on fortune_generator/json/special.json
> +      },
感恩節 is celebrated on the fourth Thursday of November.

2024-12-03 15:52 UTC, LifeAdventurer commented on fortune_generator/js/fortune.js
1. **Code Duplication**: Repeated checks (e.g., `isNaN`, range validation) could be extracted into helper functions for cleaner code.
    ```js
    function validateNumber(value, min, max, fieldName, event) {
        value = parseInt(value);
        if (isNaN(value) || value < min || value > max) {
            console.warn(`illegal event: ${fieldName} should be between ${min} and ${max}`, event);
            return null;
        }
        return value;
    }
    ```
2. **Readability**: The nested `else` and validation blocks make the code harder to read. Refactor to flatten the structure where possible.
3. **Default Behavior**: If both `week`/`weekday` and `date` are missing, consider whether a more graceful fallback (or an error throw) is appropriate rather than just logging and returning `-1`.
4. **Edge Cases**: Ensure that edge cases like invalid months (`eventMonth - 1` for zero-based indexing) or dates exceeding month limits (e.g., `31` in February) are handled properly.

2024-12-09 08:01 UTC, tobiichi3227 commented
> Wish you could separate `special.json` into three files for better organization:
> 
> 1. `static_special.json` for events with fixed dates.
> 2. `cyclical_special.json` for recurring events (e.g., holidays like Thanksgiving and Mother's Day).
> 3. `custom_special.json` for user-defined or custom events.
> 
> This separation would improve clarity and make managing different event types more efficient. Let me know what you think.

Should user-defined events also be divided into fixed dates and recurring dates?

2024-12-09 08:13 UTC, LifeAdventurer commented
> > Wish you could separate `special.json` into three files for better organization:
> > 
> > 1. `static_special.json` for events with fixed dates.
> > 2. `cyclical_special.json` for recurring events (e.g., holidays like Thanksgiving and Mother's Day).
> > 3. `custom_special.json` for user-defined or custom events.
> > 
> > This separation would improve clarity and make managing different event types more efficient. Let me know what you think.
> 
> Should user-defined events also be divided into fixed dates and recurring dates?

Yes, user-defined (custom) events should also be divided into fixed dates and recurring dates. By "custom," I mean events that don't fall into the first two categories (static or cyclical). Separating them ensures clarity and better organization across all event types.

2024-12-12 11:53 UTC, tobiichi3227 commented
User-defined events only contain static date or recurring date.
Why not simply place the user-defined events in `static_special.json` and `cyclical_special.json`?
The current `custom_special.json` is the same as the original `special.json`, containing both types.

2024-12-12 13:47 UTC, tobiichi3227 commented
OK

2024-12-12 13:49 UTC, tobiichi3227 commented
However, for events like the Moon Festival, which uses the lunar calendar and clearly occurs every year, the specific date still needs to be specified in `custom_special.json`.

2024-12-12 13:55 UTC, LifeAdventurer commented
> However, for events like the Moon Festival, which uses the lunar calendar and clearly occurs every year, the specific date still needs to be specified in `custom_special.json`.

Exactly! Your example of the Moon Festival perfectly illustrates why we need the `custom_special.json`. Events like the Moon Festival, which follows lunar calendar calculations, don't fit neatly into the standard static or cyclical event types. 

While they do occur annually, their dates can't be predetermined using a simple Gregorian calendar rule. They require specific date input each year, which makes them "custom" in nature. These events need a separate file where you can manually specify their exact dates, taking into account complex calendrical calculations.

So yes, `custom_special.json` remains crucial for handling these types of unique, annually occurring events that don't follow standard date patterns. It provides the flexibility to include events with more complex recurrence rules that can't be automatically generated.

`custom_special.json`: For one-time or **irregular events**, or **events with complex date calculations** (like the Moon Festival in the lunar calendar)

2024-12-12 13:57 UTC, LifeAdventurer commented
This is exactly what I proposed in my initial review comment!

Any special event that does not fit into either:
- Static events (fixed date every year)
- Cyclical events (recurring on a pattern like "fourth Thursday")

Goes directly into `custom_special.json`.

2024-12-12 14:19 UTC, LifeAdventurer requested changes

2024-12-12 14:19 UTC, LifeAdventurer commented on CONTRIBUTING.md
The markdown headers didn't align with the filename.

2024-12-12 14:48 UTC, merged